name: ما جديد

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 25
      - uses: gradle/actions/setup-gradle@v5
      - run: ./gradlew build
      - uses: actions/upload-artifact@v6
        with:
          name: plugin-jar
          path: build/libs/*.jar
          if-no-files-found: error
